
export const LOGIN='LOGIN'
export const LOGOUT='LOGOUT'
export const REGISTER='REGISTER'


export const EDITPROFILEPIC="EDITPROFILEPIC"
export const ADDPROFILEPIC="ADDPROFILEPIC"
export const DELETEPROFILEPIC="DELETEPROFILEPIC"

export const EDITPROFILE="EDITPROFILE"
export const TODO="TODO"